name: CI

on: [push, pull_request]

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEBUG_DEBUG: 0
  RUSTDOCFLAGS: --deny warnings
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt
      - name: cargo fmt -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        features:
          - std
          - std,json-ld
          - std,serde
          - std,bin-ldsig2017
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Rustdoc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose --no-default-features '--features=${{ matrix.features }}' --no-deps
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --tests --no-default-features '--features=${{ matrix.features }}' -- --deny warnings
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --tests --no-default-features '--features=${{ matrix.features }}'
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --no-default-features '--features=${{ matrix.features }}'
      - name: Clippy binary
        if: contains(matrix.features, 'bin-ldsig2017')
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --verbose --bin ldsig2017 --no-default-features '--features=${{ matrix.features }}' -- --deny warnings
